# Generated by Django 3.0.5 on 2020-07-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_auto_20200616_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydefinition',
            name='resident_discount',
            field=models.FloatField(
                default=0.25,
                help_text='Discount applicable to Balearic islands residents'
            ),
        ),
    ]
