version: "3"
services:

  db:
    image: postgres:12
    env_file: .env
    volumes:
      - boatsandjoy-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  boatsandjoy-api:
    build:
      context: .
    env_file: .env
    volumes:
      - ".:/code"
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - PYTHONIOENCODING=UTF-8
      - PYTHONUNBUFFERED=1
    command: wait-for-it -t 0 db:5432 -- python /code/manage.py runserver 0.0.0.0:80

  ngrok:
    image: wernight/ngrok
    ports:
      - "4041:4040"
    depends_on:
      - boatsandjoy-api
    command: ngrok http boatsandjoy-api:80 -host-header="localhost:80"

volumes:
  boatsandjoy-data: {}
