# Generated by Django 3.0.5 on 2020-06-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydefinition',
            name='discount_when_deal',
            field=models.FloatField(default=0.0, help_text='Discount applied when availability result is composed by more than n_slots_deal_threshold slots'),
        ),
        migrations.AddField(
            model_name='daydefinition',
            name='n_slots_deal_threshold',
            field=models.IntegerField(default=0, help_text='Number of slots that has to have an availability result to be considered as a good deal'),
        ),
    ]
