# Generated by Django 3.2.10 on 2022-02-26 17:07

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('factor', models.FloatField(help_text='You can use it to define discounts with numbers less than 0 Ex: if you need a 20% discount you have to specify 0.8, if you need to increase price a 50%, you have to specify 1.5 value')),
                ('limit_of_uses', models.IntegerField(default=10)),
                ('number_of_uses', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'promocode',
                'verbose_name_plural': 'promocodes',
            },
        ),
    ]
