# Generated by Django 3.2.10 on 2022-02-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='limit_of_uses',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='promocode',
            name='number_of_uses',
            field=models.IntegerField(default=0),
        ),
    ]
