# Generated by Django 3.2.10 on 2022-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promocode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
