# Generated by Django 2.2.9 on 2020-02-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='locator',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
